query blogs($pageIndex: Int!, $pageSize: Int!){
  blogs(pageIndex: $pageIndex, pageSize: $pageSize) {
    list {
      _id
      title
      createDate
      ispublish
      author {
        nickname
      }
      category {
        text
      }
    }
    pagination {
      total
      pageIndex
      pageSize
    }
  }
}