query blog ($id: String!) {
  blog(id: $id) {
    title
    summary
    content
    banner
    unionname
    tags
    keywords
    category {
      text
      value
      _id
    }
  }
  menus {
    text
    _id
  }
  config {
    domain
  }
}